### ISSUE TITLE
Bug report scan_chunk

### ISSUE THREAD

**Issue by GEADR** [Fenixin/Minecraft-Region-Fixer#173] opened 2021-12-13 13:22 UTC
Welcome to Region Fixer!
(v 0.3.4)

############################################################
############################################################

World info:
 - 79 region/level files,
 - 34 POI files,
 - 56 entities files,
 - 32 player files,
 - and 5 data files.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
32 of 32|########################################################|Time: 0:00:00

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------
5 of 5|##########################################################|Time: 0:00:00

--------- Scanning region, POI and entities files ----------
0 of 169|                                                       |ETA:  --:--:--

Ops! Something went really wrong and regionfixer crashed.

Bug report:

**********
*** Exception while scanning:
*** r.-1.-1.mca
**********
*** Printing the child's traceback:
*** Exception:<class 'AssertionError'>Unrecognized scanned chunk in scan_chunk().
**********
*** File C:\Users\GEADR\Desktop\MR\MR\regionfixer_core\scan.py, line 810, in scan_region_file
***   chunk, tup = scan_chunk(region_file,**********
*** File C:\Users\GEADR\Desktop\MR\MR\regionfixer_core\scan.py, line 996, in scan_chunk
***   raise AssertionError("Unrecognized scanned chunk in scan_chunk().")
**********

**Comment by 734F96** [comment] 2021-12-16 21:37
Hello,
Is it an 1.18 world ? If it is, your issue is a duplicate of issue #172.
You can see 1.18 WIP support in PR #169 ! ^^
Have a nice day !

**Comment by Fenixin** [comment] 2021-12-19 21:37
Hello!

I have just merged #169 from @734F96. I'm closing this, feel free to open/reopen if you have any problem.

**Closed by Fenixin** 2021-12-19 21:37 UTC
Labels: Bug
