### ISSUE TITLE
ImportError: cannot import name world

### ISSUE THREAD

**Issue by mwaning** [Fenixin/Minecraft-Region-Fixer#93] opened 2019-09-12 13:54 UTC
Dear Fenixin,
Thank you for the effort of creating this program. It would be a great help since some of my worlds are getting corrupted in the new updates.
However, I'm currently having some issues getting it to work. It seems to give the same error messages no matter what I ask regionfixer.py to do. This is the output of my CMD log:

```
C:\Users\marco\Downloads\Minecraft-Region-Fixer-master>regionfixer.py C:\Users\marco\Downloads\FixRegions\world
Traceback (most recent call last):
  File "C:\Users\marco\Downloads\Minecraft-Region-Fixer-master\regionfixer.py", line 29, in <module>
    from regionfixer_core import world
  File "C:\Users\marco\Downloads\Minecraft-Region-Fixer-master\regionfixer_core\world.py", line 26, in <module>
    from .util import table
  File "C:\Users\marco\Downloads\Minecraft-Region-Fixer-master\regionfixer_core\util.py", line 27, in <module>
    from . import world
ImportError: cannot import name world

C:\Users\marco\Downloads\Minecraft-Region-Fixer-master>regionfixer.py --help
Traceback (most recent call last):
  File "C:\Users\marco\Downloads\Minecraft-Region-Fixer-master\regionfixer.py", line 29, in <module>
    from regionfixer_core import world
  File "C:\Users\marco\Downloads\Minecraft-Region-Fixer-master\regionfixer_core\world.py", line 26, in <module>
    from .util import table
  File "C:\Users\marco\Downloads\Minecraft-Region-Fixer-master\regionfixer_core\util.py", line 27, in <module>
    from . import world
ImportError: cannot import name world
```

**Comment by Mick00** [comment] 2019-09-16 02:32
I think you might be using Python 2 and this projects works with Python 3

**Comment by mwaning** [comment] 2019-09-16 06:43
Hi Mick, thanks for the advice. I do really think that it should be Python 3.something, but I'll make sure when I can and let you know.

**Comment by Fenixin** [comment] 2019-09-18 18:33
Hello!

As Mick00 says, it looks like you are using python2 instead of python3. This program only works on python3.

Please try again with python3 and clos this if the issue is solved.

**Comment by Fenixin** [comment] 2019-09-19 21:01
I'm going to close this, feel free to open a new issue if you still have problems

**Closed by Fenixin** 2019-09-19 21:01 UTC
Labels: Waiting for user

**Comment by toastkid** [comment] 2020-06-06 10:41
I'm experiencing this same problem with python3: 

```
$ python3 ./regionfixer.py "arlo_world/level.dat"
Traceback (most recent call last):
  File "./regionfixer.py", line 29, in <module>
    from regionfixer_core import world
  File "/home/max/software/minecraft/Minecraft-Region-Fixer/regionfixer_core/world.py", line 26, in <module>
    from .util import table
  File "/home/max/software/minecraft/Minecraft-Region-Fixer/regionfixer_core/util.py", line 27, in <module>
    from . import world
ImportError: cannot import name 'world'
```

**Comment by Fenixin** [comment] 2020-06-17 21:51
@toastkid, hey, you can open a new issue instead of using this really old one. That said, have you solved your problem?

**Comment by voronkovventures** [comment] 2021-01-18 11:20
Hello! I am running python script for minecraft using raspberry juice and have the same issue. How to fix it? I am trying to use python scripts from educational Minecraft in RaspberryJuice minecraft.

"root@Rontgen:~/Bukkit/plugins# python3 blocks.py
Traceback (most recent call last):
  File "blocks.py", line 1, in <module>
    from mc import world, blocks, player
ImportError: cannot import name 'world' from 'mc' (/usr/local/lib/python3.8/dist-packages/mc/__init__.py)
root@Rontgen:~/Bukkit/plugins# "

**Comment by voronkovventures** [comment] 2021-01-18 11:20
Hello! I am running python script for minecraft using raspberry juice and have the same issue. How to fix it? I am trying to use python scripts from educational Minecraft in RaspberryJuice minecraft.

"root@Rontgen:~/Bukkit/plugins# python3 blocks.py
Traceback (most recent call last):
  File "blocks.py", line 1, in <module>
    from mc import world, blocks, player
ImportError: cannot import name 'world' from 'mc' (/usr/local/lib/python3.8/dist-packages/mc/__init__.py)
root@Rontgen:~/Bukkit/plugins# "
