### ISSUE TITLE
Not a String error in 1.16.x

### ISSUE THREAD

**Issue by uncovery** [Fenixin/Minecraft-Region-Fixer#132] opened 2020-09-10 02:53 UTC
**Is your feature request related to a problem? Please describe.**
There is a datatype issue with 1.16 where the dimension variable in .dat/data entries used to be stored as a int and should now be a string. In 1.16, this results in "not a string" errors. See here : https://github.com/Multiverse/Multiverse-Core/issues/2317#issuecomment-689629419

**Describe the solution you'd like**
Automatically recognizing the issue with the file and fixing it.

**Describe alternatives you've considered**
deleting the .dat...

**Comment by Fenixin** [comment] 2020-09-10 06:16
Hello!

Is this a problem with minecraft vanilla or only happens with modded worlds? I'm afraid that trying to keep up with mods and trying to fix the nbt types are two time consuming task that I don't want to do.

So, if it's not a bug in vanilla I won't add it to RegionFixer.

**Comment by benwoo1110** [comment] 2020-10-11 04:07
It is reported that its fixed in paper [build #220](https://github.com/PaperMC/Paper/commit/f3927b25ebb6cff982a97d82cb424c137fedac9f)

**Comment by Fenixin** [comment] 2020-10-17 22:04
I'm closing this. This seems to be fixed somewhere else. Feel free to open a new issue if you think it's not.

**Closed by Fenixin** 2020-10-17 22:04 UTC
Labels: Feature request
