### ISSUE TITLE
Error when running on 1.13.1

### ISSUE THREAD

**Issue by robotnikthingy** [Fenixin/Minecraft-Region-Fixer#64] opened 2018-09-09 20:39 UTC
I get this error when trying to run the region fixed on one of my worlds

https://pastebin.com/0kYMjRkK

I deleted the fortress.dat file to see if that helped, but it then runs into this error

https://pastebin.com/80LUiDZ0

**Comment by robotnikthingy** [comment] 2018-09-09 20:42
Just realized I wasn't using the version from the 1.13-update branch

I ran it again and it went smoothly until it ran into another error

https://pastebin.com/fVkPaAYR

**Comment by macfreek** [comment] 2018-09-10 07:37
Glad the former two errors are fixed with the new NBT version. The later error seems to be an issue with Minecraft-Region-Fixer: it's looking for Entities in the file, but there is no Entities tag present. That could be either due to a corrupt chunk, or a change in the chunk format. I get the impression that @Fenixin is currently not an active Minecraft player anymore (I also don't play it actively anymore).

Would it be possible for you to upload `r.6.-10.mca` and another (good) file from your world? That would allow us to reproduce the error that you see. If you rather share it in private, or not at all, let us know, and we try to work something out.

Just a small heads up: I know that @Fenixin is busy at the moment, and so am I, so you might have to put in some work yourself to get support.

**Comment by robotnikthingy** [comment] 2018-09-11 01:44
I don't mind uploading the chunks

heres the region with the error
https://drive.google.com/open?id=1YR5Poo76PX94KeMXrMcF6ElzlCsokFSN

heres a good region
https://drive.google.com/open?id=1ufWg0PzF9f7CdMFgdPA1_T7UTxgdpbHM

**Comment by Fenixin** [comment] 2019-02-17 23:23
Sorry for the late answer and thanks for the bug report.

I've downloaded the files and I plan to give them a look soon.

**Comment by Fenixin** [comment] 2019-02-21 23:59
Hello!

So as far as I know, using the [miencraft wiki](https://minecraft.gamepedia.com/Chunk_format) as reference, chunks should have an entities tag. Also there seems to be a other issues with the same problem (see #67). I have also created a minecraft world with a few regions and all the chunks seems to have the Entities tag.

That said I have just added this new problem to regionfixer, see this branch (which includes a few more changes): https://github.com/Fenixin/Minecraft-Region-Fixer/tree/new2to3

Thanks for the bug report!

**Comment by Fenixin** [comment] 2019-04-16 09:54
See issue #75 for more information about this. The current version, in branch [new2to3](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/new2to3) can detect and delete chunks with this problem. The ideal would be to fix them, but it's not yet implemented.

I'm closing this issue. Feel free to reopen it if you have any new information or somethingn to say.

**Closed by Fenixin** 2019-04-16 09:54 UTC
