### ISSUE TITLE
Can't seem to get region-fixer to run.

### ISSUE THREAD

**Issue by stubbornpirate** [Fenixin/Minecraft-Region-Fixer#134] opened 2020-09-28 22:07 UTC
I am unable to get region fixer to run, when I type commands into cmd or try to launch regionfixer.py or regionfixer_gui.py, a black box flashes for a second then disappears. 

cmd log

C:\Users\Travis>cd F:\Users\Travis\Documents\McRegionFixer

C:\Users\Travis>regionfixer.py --help

C:\Users\Travis>regionfixer.py -p 4 --deletecorrupted F:\Users\Travis\Documents\mcforgeserver\world

C:\Users\Travis>cd F:\Users\Travis\Documents\McRegionFixer

C:\Users\Travis>python regionfixer.py F:\Users\Travis\Documents\mcforgeserver\world

from a few video tutorials I've seen, there should be a lot of lines created after running the commands or the python files, but nothing happens

 - Windows 10
 - Python 3.8 downloaded from microsoft store
 - Region Fixer downloaded from github 9/27/20

**Comment by Fenixin** [comment] 2020-09-29 16:46
Hello!

From your commands:
```
C:\Users\Travis>cd F:\Users\Travis\Documents\McRegionFixer
C:\Users\Travis>regionfixer.py --help
C:\Users\Travis>regionfixer.py -p 4 --deletecorrupted F:\Users\Travis\Documents\mcforgeserver\world
C:\Users\Travis>cd F:\Users\Travis\Documents\McRegionFixer
C:\Users\Travis>python regionfixer.py F:\Users\Travis\Documents\mcforgeserver\world
```
It seems that you never changed your folder to `F:\Users\Travis\Documents\McRegionFixer`. You need to be in the directory of RegionFixer in order to run it.

Please, try changing the directory to the regionfixer directory and try again.

Also, it's very strange that nothing is printed, could you try to restart your computer and issuing a `python --version` and see if that prints anything.

**Comment by stubbornpirate** [comment] 2020-09-29 22:10
"python --version" prints 3.8.6

isn't "cd F:Users\Travis\Documents\McRegionFixer" switching to the region fixer folder?

**Comment by Fenixin** [comment] 2020-09-30 16:06
Well, maybe, it depends on where did you decompress the files. I think the problem is that you have to change F to C:

`cd C:\Users\Travis\Documents\McRegionFixer`

But I don't know, you should know where your files are.

**Comment by stubbornpirate** [comment] 2020-09-30 23:21
Yep I can confirm its on my F drive, I just copied and pasted the folder path from the top.

**Comment by Fenixin** [comment] 2020-10-02 09:16
> 
> 
> Yep I can confirm its on my F drive, I just copied and pasted the folder path from the top.

Then, something is really wrong, in the comment you posted says:

```
C:\Users\Travis>cd F:\Users\Travis\Documents\McRegionFixer
C:\Users\Travis>regionfixer.py --help
C:\Users\Travis>regionfixer.py -p 4 --deletecorrupted F:\Users\Travis\Documents\mcforgeserver\world
C:\Users\Travis>cd F:\Users\Travis\Documents\McRegionFixer
C:\Users\Travis>python regionfixer.py F:\Users\Travis\Documents\mcforgeserver\world
```

After the command `cd F:\Users\Travis\Documents\McRegionFixer` it should say something like:

```
F:\Users\Travis\Documents\McRegionFixer>
```
If it doesn't change your directory isn't changing. Please confirm where is your installation of regionfixer and that you are changing directory properly. Maybe a screenshot would help to confirm that you are writing the commands properly.

**Comment by stubbornpirate** [comment] 2020-10-04 15:34
Yeah, it seems like the directory isn't changing for whatever reason.
![Region Fixer Screenshot](https://user-images.githubusercontent.com/71998408/95019809-83d8f800-0635-11eb-964f-99dc8c6c7c4d.png)
![CMD Screenshot](https://user-images.githubusercontent.com/71998408/95019811-850a2500-0635-11eb-926f-cfda208c8b32.png)

**Comment by Fenixin** [comment] 2020-10-04 21:02
Something strange is happening, please, try to fix that and then try running regionfixer again.

I would like to help with this but I have no idea what's going on.

**Comment by stubbornpirate** [comment] 2020-10-05 02:59
Alright, I moved both folders to my C drive. It's still not running, but it did pop open a second window this time.
![Screenshot (5)](https://user-images.githubusercontent.com/71998408/95036201-2c6a7480-0695-11eb-88a4-793e93b10d47.png)

**Comment by Fenixin** [comment] 2020-10-05 18:06
That's really strange. That window should only pop up when you are double clicking the executable. I don't know what is it but there is something strange with your ms-dos command line iterface.

How do you open your CLI? Is there something strange with your system? Could you try regionfixer in another computer?

**Comment by stubbornpirate** [comment] 2020-10-05 18:13
for opening it, just typed cmd in the start bar, and launched it both in admin and normal.

I had my friend also try to run it, similar situation. I'm pretty sure he had both folders already on his C drive.

**Comment by stubbornpirate** [comment] 2020-10-05 23:42
my friend ended up going to his region-fixer directory, and running python while in the directory, then running region-fixer. He was able to run it, but unfortunately for us no corruption was found.

Thanks for your support.

**Comment by Fenixin** [comment] 2020-10-07 17:08
Could you please tell me how did you solve the problem so if it happens again I can help other people?

**Comment by Fenixin** [comment] 2020-10-17 22:00
Closing this, it would be helpful to know what did you do. Feel free to comment in the closed issue.

**Closed by Fenixin** 2020-10-17 22:00 UTC
