### ISSUE TITLE
Crash after try to fix chunk

### ISSUE THREAD

**Issue by freaki2010** [Fenixin/Minecraft-Region-Fixer#135] opened 2020-10-06 20:04 UTC
**Describe the bug**
I run a modded server on which the [following error](https://haste.gafert.org/ewesavexib.css) has been spammed for about 1 1/2 months. After a long manual search I found your Python scrip today. I was able to find the problem within a few minutes. There was a chunk corrupted in the DIM7. I didn't find this out by the endreport but by a crash when I tried to fix this chunk. My Command + Output I add following.

**Full copied text from the MS-DOS view**
https://haste.gafert.org/qicifiwuyu.coffeescript

**Expected behavior**
I expected the corrupt chunk to be fixed and not the program to crash.

**Files that would help solving the issue**
I only upload the DIM7 to my Nextcloud, so you don't have to download 3GB worldfiles, of which you only need 300MB in the end.
https://next.ender.io/s/raSokKoAqLJRPHw

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.8
 - Region Fixer Version (v 0.3.3)

**Additional context**
The modpack to the world is [Novus Remix](https://www.technicpack.net/modpack/novus-bevo.872537). The world is a RFTools world. If you need the whole world I can upload it to my Nextcloud!

**Comment by Fenixin** [comment] 2020-10-07 17:04
Thank you very much for your well structured bug report.

As you say this looks like a bug. I'm currently downloading the world files and I will test this to see what's wrong.

**Comment by freaki2010** [comment] 2020-10-13 19:16
Hey, is there any news yet? and were you able to reproduce the error? 
Thanks a lot for your efforts!

**Comment by Fenixin** [comment] 2020-10-13 19:47
I'm afraid not, busy week. I hope to give it a look tomorrow or in the weekend.

**Comment by Fenixin** [comment] 2020-10-17 21:46
It seems that the dimension you sent me is completely fine. After the scan there is nothing wrong and I can't reproduce the problem. I don't know if you have that offending region file still around but it would be really useful for fixing the bug (to reproduce this I only need the single region file with the corrupted chunk). Meanwhile I'm going to try to reproduce this in oder ways.

**Comment by Fenixin** [comment] 2020-10-17 21:59
So, this _might_ be fixed in the branch [bugfix](https://github.com/Fenixin/Minecraft-Region-Fixer/tree/bugfix). The bad news is that if it's really fixed for you that means your chunk can't be fixed (at least for now). Tell me how this works for you, if it's not fixed having the regionfile would help wonders.

**Comment by Fenixin** [comment] 2021-11-06 22:51
The issue is pretty old, I'm closing it. Feel free to reopen it if you need anything else.

**Closed by Fenixin** 2021-11-06 22:51 UTC
Labels: Bug
