### ISSUE TITLE
Not replacing deleted chunk with proper chunk info:

### ISSUE THREAD

**Issue by LegendaryAdmin** [Fenixin/Minecraft-Region-Fixer#43] opened 2015-06-17 17:03 UTC
Running on windows, used the latest region fixer tool as of june 16th, running latest python as of the same date. I ran the scan on Saturday, it told me the regions were fixed. Players started logging in, and a few people were still caught in corrupt chunks and the server started crashing again. I looked around and found things like this:

http://i.imgur.com/GJmI2P4.jpg
and
http://i.imgur.com/PrvvtyU.jpg

So I downloaded the the world again, run the region fixer and it tells me the exact same number of chunks are still corrupt. After using region fixer, I do a second scan and it tells me the chunks are fine, but it looks the exact same with the scattered chunks.

It appears that the region fixer is not deleting a bad chunk, but replacing a bad chunk with a set of default chunks of some sort. and scattering others... =[ In the second image you can clearly see the same chunk being used in 3 chunks out of a 4 chunk pocket. Very confused as to what I need to do...

**Comment by Fenixin** [comment] 2015-06-17 21:12
Hello!

Sorry for the problem, it's a really strange one!

Althought this is obvious I have to ask: have you uploaded your world correctly to the server after fixing it? It's really strange that you download the world, scan and fix it, then download it again and find exactly the same problems as before. It really sounds as something is missing in the download/upload process.

AFAIK region-fixer can't replace a random chunk from a place to another in random fashion. And it's even more strange if you are not using any of the replace options (I guess from your report that you are only removing chunks). If deleting the chunks and the rescanning gives you no bad chunks, then I think the problem is in the download/upload or the server itself. To test this you could fix the world in your local pc and then test it yourself (start server and move to the problematic zone/chunks/regions, see if those copied chunks are there).

That said, is there anything else that you can tell me about your world/server that could help in understanding what's going on?

**Comment by LegendaryAdmin** [comment] 2015-06-18 00:08
I ran the first upload while I was sleeping, and I have a feeling at some point my net cut out because the next day it took nearly 18 hours to upload the same files. So I believe there was a problem with the first upload process. 

Those pictures are taken after the second upload, however.

We are running the tool directly on the machine now and replacing with backups. Keep your fingers crossed for me =]

**Comment by Fenixin** [comment] 2019-04-16 10:17
This is oudated so I'm going to close this.

Please, feel free to open a new issue if you still had the problem.

**Closed by Fenixin** 2019-04-16 10:17 UTC
