### ISSUE TITLE
Delete corrupt chunks doesnt delete POI for that chunk.

### ISSUE THREAD

**Issue by TacoFluffy4** [Fenixin/Minecraft-Region-Fixer#104] opened 2020-03-22 18:10 UTC
My world has a few corrupt POI that crash the game when they are loaded. Running this program deletes the chunk but not the associated POI for the chunk, so next time they are regenerated, they will still crash the game.

**Comment by Fenixin** [comment] 2020-03-22 19:41
Hello!

Sorry, I don't know what a POI is, if the chunk has been removed there is no way is crashing the game again unless there is some other stuff somewhere.

Could you tell me what a POI is? Where is stored? Are you using mods?

**Comment by TacoFluffy4** [comment] 2020-03-22 19:54
I was using vanilla. I'm not 100% sure on the technical details, but POIs were added in 1.14 as a replacement for villages.dat I think it contains information for things like villager workstations and now bee hive locations, They are stored in the POI folder as opposed to the region folder which is likely why they don't get deleted. I only know that it has to do with the POIs because if i delete all the regions and regenerate the chunks the crash persists, but if i delete all the POIs the game stops crashing.

**Comment by Fenixin** [comment] 2020-03-31 21:19
Hey, you are completely right, I don't follow mincraft development right now so I didn't know about POIs. I'm afraid that regionfixer can't scan/fix/remove POIs right now.

If I end up unoccupied this quarentine I will update regionfixer with this, thanks for the report.

**Comment by Fenixin** [comment] 2020-07-21 09:50
Hello!

I have added basic sanning of POI files to regionfixer. Would you be able to test this with your world or send me the world so I can test this?

Right now it only scans the POIs to look for corruption in the compressed stream, but it doesn't remove the POIs if a chunk is corrupted. That is why I want a way to test this.

**Comment by TacoFluffy4** [comment] 2020-07-21 19:34
I tested the bugfix branch on a backup of my world with the issue, and it did fix the issue. I don't know if you need it, but I could send you the world if you want to test it yourself, The only problem is that my world is rather large so I can't send you the whole thing, but I could send a version with the problematic region/poi files.

**Comment by Fenixin** [comment] 2020-07-21 20:10
Thank you very much for your answer. A subset of the world with the region files and their corresponding region-poi files would very helpful to test this.

You can post here a download link or send me a email to fenixin at gmail dot com.

**Comment by Fenixin** [comment] 2020-07-23 09:10
Your world was very helpful, it pointed to new bug in regionfixer and it's already fixed. About POIs and logging: regionfixer logs POIs scanning, the problem is that it logs it as it were normal chunks and normal region files. This is because **they are normal region files** and normal chunks.

The structure in the region file is exactly the same. And inside the region file there are NBT files. Chunks are NBT files and pois are exactly the same thing. The only thing that change is the contents of the NBT files.

I probably should clarify this somehow in the scanning process, maybe adding a new progress bar for POIs, or adding 'poi' to the filename in verbose mode.

Anyway, thanks you very much for you time and your files. I'm going to leave this open so I remember to clarify that.

**Comment by Fenixin** [comment] 2020-07-23 09:36
Now when scanning in --verbose mode the last directory where the region file/data file is, will be printed. I'm closing this. Feel free to open a new issue if you need anything else.

**Closed by Fenixin** 2020-07-23 09:36 UTC
Labels: Bug, Feature request
