### ISSUE TITLE
Cannot start regionfixer..

### ISSUE THREAD

**Issue by SajmonOriginal** [Fenixin/Minecraft-Region-Fixer#90] opened 2019-08-16 23:01 UTC
Hello i cant start regionfixer anymore.. when i type the command and hit enter nothing will happen and if i try to use RegionFixer on Ubuntu it says this:

`Traceback (most recent call last):
  File "regionfixer.py", line 29, in <module>
    from regionfixer_core import world
  File "/home/******/Minecraft/Java/Vanilla/RF/Minecraft-Region-Fixer/regionfixer_core/world.py", line 26, in <module>
    from .util import table
  File "/home/******/Minecraft/Java/Vanilla/RF/Minecraft-Region-Fixer/regionfixer_core/util.py", line 27, in <module>
    from . import world
ImportError: cannot import name world
`

**Comment by UnioDex** [comment] 2019-08-17 13:42
I have the same issue. Ubuntu 18.04:

```
Traceback (most recent call last):
  File "regionfixer.py", line 29, in <module>
    from regionfixer_core import world
  File "/home/server/Skyblock/regionfixer/0.3.1/Minecraft-Region-Fixer-0.3.1/regionfixer_core/world.py", line 26, in <module>
    from .util import table
  File "/home/server/Skyblock/regionfixer/0.3.1/Minecraft-Region-Fixer-0.3.1/regionfixer_core/util.py", line 27, in <module>
    from . import world
ImportError: cannot import name world
```

It only started to happen with 0.3.1 version.

**Comment by Fenixin** [comment] 2019-09-18 18:46
Hello!

This looks like you are using python2 instead of the mandatory python3. Regionfixer will only work with python3. 

Please, try to use it with python3 and report back.

**Comment by Scheshi** [comment] 2020-01-12 08:14
![image](https://user-images.githubusercontent.com/47576867/72216038-56a95000-34d0-11ea-8edc-4e655b312d5e.png)
@Fenixin I don't think that's the problem.

**Comment by Fenixin** [comment] 2020-01-12 09:33
From your screenshot I see that you are scanning a region directory, could you please try to scan the world folder or add *.mca at the end of the command prompt? I will try to reproduce this.

**Comment by Scheshi** [comment] 2020-01-12 09:39
![Screenshot_20200112_163845](https://user-images.githubusercontent.com/47576867/72216919-08409380-355a-11ea-8039-d43bad398b28.jpg)

**Comment by Fenixin** [comment] 2020-01-12 15:11
@Scheshi, In your last image you are using `python` when invoking `regionfixer.py` but `python3` when calling for version. In my ubutu system if I use `python` python 2 is ran, and if I use python3 the version 3 is ran. Like this:
```
$ python --version
Python 2.7.17
$ python3 --version
Python 3.6.9
```
Could you please test regionfixer with python3 instead of python?

**Comment by Scheshi** [comment] 2020-01-12 15:47
Yes, it working with python3. Thank you for help!

**Comment by Fenixin** [comment] 2020-01-12 15:51
I'm going to close this, the issue seems to be python version.

**Closed by Fenixin** 2020-01-12 15:51 UTC
Labels: Waiting for user
