### ISSUE TITLE
Ops! Something went really wrong and regionfixer crashed.

### ISSUE THREAD

**Issue by TickleMeHomo7** [Fenixin/Minecraft-Region-Fixer#155] opened 2021-04-11 16:09 UTC
```
C:\Users\scsin\Desktop\Minecraft-Region-Fixer-master>regionfixer.py -p 4 --fc C:\Users\scsin\Desktop\mccopy\world

Welcome to Region Fixer!
(v 0.3.3)

############################################################
#################  Scanning world: world  ##################
############################################################

World info:
There are 250 region files, 6 player files and 5 data files in the world directory.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
2 of 6|###################                                       |ETA:  0:00:00

Ops! Something went really wrong and regionfixer crashed.


Bug report:

**********
*** Exception while scanning:
*** 53b495ab-6c48-40be-b4d0-5dddcb3c331d.dat
**********
*** Printing the child's traceback:
*** Exception:<class 'zlib.error'>Error -3 while decompressing data: invalid stored block lengths
**********
*** File C:\Users\scsin\Desktop\Minecraft-Region-Fixer-master\regionfixer_core\scan.py, line 746, in scan_data
***   _ = nbt.NBTFile(filename=s.path)**********
*** File C:\Users\scsin\Desktop\Minecraft-Region-Fixer-master\nbt\nbt.py, line 628, in __init__
***   self.parse_file()**********
*** File C:\Users\scsin\Desktop\Minecraft-Region-Fixer-master\nbt\nbt.py, line 652, in parse_file
***   type = TAG_Byte(buffer=self.file)**********
*** File C:\Users\scsin\Desktop\Minecraft-Region-Fixer-master\nbt\nbt.py, line 99, in __init__
***   self._parse_buffer(buffer)**********
*** File C:\Users\scsin\Desktop\Minecraft-Region-Fixer-master\nbt\nbt.py, line 105, in _parse_buffer
***   self.value = self.fmt.unpack(buffer.read(self.fmt.size))[0]**********
*** File C:\Users\scsin\AppData\Local\Programs\Python\Python39\lib\gzip.py, line 300, in read
***   return self._buffer.read(size)**********
*** File C:\Users\scsin\AppData\Local\Programs\Python\Python39\lib\_compression.py, line 68, in readinto
***   data = self.read(len(byte_view))**********
*** File C:\Users\scsin\AppData\Local\Programs\Python\Python39\lib\gzip.py, line 495, in read
***   uncompress = self._decompressor.decompress(buf, size)
**********
```

**Comment by Fenixin** [comment] 2021-11-06 21:45
Hello!

Sorry for the late answer.

Could you send the file? I mean the "53b495ab-6c48-40be-b4d0-5dddcb3c331d.dat" player file, so I can reproduce and fix this. 

I'm going to close this issue because it's very old, don't hesitate to reopen and send me the file so I can try to debug this.

**Closed by Fenixin** 2021-11-06 21:45 UTC
Labels: Bug
