### ISSUE TITLE
Any way to repair Unreadable data files: idcounts.dat ?

### ISSUE THREAD

**Issue by lulabyte** [Fenixin/Minecraft-Region-Fixer#138] opened 2020-10-22 20:27 UTC
**Describe the bug**
A world that I can load into once, save, and exit, cannot be loaded again (freezes on "Reading World Data"). When I run Region Fixer the only error I get is:

Unreadable data files:
idcounts.dat

Is it possible to fix this? I don't care of maps are deleted, and I can actually do things in-game, save and exit if that's helpful towards any solution. It's when I try to reload the save that it hangs up on "Reading World Data".

**Full copied text from the MS-DOS view**
```
Microsoft Windows [Version 10.0.19041.572]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\lulab>cd C:\Users\lulab\Downloads\Minecraft-Region-Fixer-0.3.3

C:\Users\lulab\Downloads\Minecraft-Region-Fixer-0.3.3>python regionfixer_gui.py
Traceback (most recent call last):
  File "C:\Users\lulab\Downloads\Minecraft-Region-Fixer-0.3.3\regionfixer_gui.py", line 11, in <module>
    from gui import Starter
  File "C:\Users\lulab\Downloads\Minecraft-Region-Fixer-0.3.3\gui\__init__.py", line 4, in <module>
    from .main import MainWindow
  File "C:\Users\lulab\Downloads\Minecraft-Region-Fixer-0.3.3\gui\main.py", line 4, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

C:\Users\lulab\Downloads\Minecraft-Region-Fixer-0.3.3>python regionfixer.py C:\Users\lulab\AppData\Roaming\.minecraft\saves\Friendship World
Warning: The folder C:\Users\lulab\AppData\Roaming\.minecraft\saves\Friendship doesn't exist. I'll skip it.
Warning: The folder World doesn't exist. I'll skip it.

Welcome to Region Fixer!
(v 0.3.3)
Error: No worlds or region files to scan! Use --help for a complete list of options.

C:\Users\lulab\Downloads\Minecraft-Region-Fixer-0.3.3>C:\Users\lulab\AppData\Roaming\.minecraft\saves\FriendshipWorld
'C:\Users\lulab\AppData\Roaming\.minecraft\saves\FriendshipWorld' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\lulab\Downloads\Minecraft-Region-Fixer-0.3.3>python regionfixer.py C:\Users\lulab\AppData\Roaming\.minecraft\saves\FriendshipWorld

Welcome to Region Fixer!
(v 0.3.3)

############################################################
##########  Scanning world: Friendship World 1.0  ##########
############################################################

World info:
There are 513 region files, 5 player files and 38 data files in the world directory.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
5 of 5|##########################################################|Time: 0:00:00

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------
38 of 38|########################################################|Time: 0:00:00

------------------ Scanning region files -------------------
513 of 513|######################################################|Time: 0:08:58


############################################################
########## Scan results for: Friendship World 1.0 ##########
############################################################

Unreadable player files:
No problems found.

Unreadable data files:
idcounts.dat

Chunk problems:
No problems found.

Region problems:
No problems found.

C:\Users\lulab\Downloads\Minecraft-Region-Fixer-0.3.3>

```
**Expected behavior**
To be able to load my world.

**Screenshots**

**Files that would help solving the issue**
idcounts.dat

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.9
 - Region Fixer Version 0.3.3

**Additional context**
Any help would be appreciated, I've tried everything I can find online!

**Comment by Fenixin** [comment] 2020-10-24 17:31
Hello!

That is very strange indeed. You could try to remove idcounts.dat and all the maps.

Answering your question, it might be possible to fix idcounts.dat but regionfixer is not going to do that in the foreseeable future. So the best thing to try is to remove `idcounts.dat` and remove every `map_<numbre>.dat` file in the `data` directory. This could work.

Please, try that and report back if that works.

**Comment by SkilledAlpaca** [comment] 2020-10-24 21:56
Interestingly enough I also had the same issue with a corrupted `idcounts.dat`. Attempting the fix you proposed to delete the `idcounts.dat` and `map_<number>,dat`  didn't resolve the issue I'm having though but it was worth a shot. I've placed my console output below as well in-case it somehow helps. 

```
PS E:\Minecraft Servers\Minecraft-Region-Fixer-master> python regionfixer.py -p 8 "E:\Minecraft Servers\world"

Welcome to Region Fixer!
(v 0.3.3)

############################################################
#################  Scanning world: world  ##################
############################################################

World info:
There are 541 region files, 10 player files and 19 data files in the world directory.

-------------------- Checking level.dat --------------------
'level.dat' is readable

---------------- Scanning UUID player files ----------------
10 of 10|########################################################|Time: 0:00:00

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------
19 of 19|########################################################|Time: 0:00:01

------------------ Scanning region files -------------------
541 of 541|######################################################|Time: 0:01:59


############################################################
################# Scan results for: world ##################
############################################################


Unreadable player files:
No problems found.

Unreadable data files:
idcounts.dat

Chunk problems:
No problems found.


Region problems:
No problems found.
```

**Comment by Fenixin** [comment] 2020-10-27 19:00
@SkilledAlpaca, so, after removing all those data files and getting a clean scan by regionfixer, the worls still doesn't load in minecraft? That's very strange.

I can say that I'm completely lost. Have you tried to load/create another world? Could you upload the world to test it myself? I'm going to be very busy the next weeks but if I get a moment I will give a look.

**Comment by SkilledAlpaca** [comment] 2020-10-27 22:50
My apologies, my world has always worked and has no issues loading. I'm dealing with a strange problem where when my server shuts down, it just hangs until I manually kill it. One of my troubleshooting steps was to check and see if the issue was caused by invalid or corrupted chunks using your utility. The only error I got was for the `idcounts.dat` being unreadable.

**Comment by Fenixin** [comment] 2020-11-09 21:09
@SkilledAlpaca, no idea what's going on. To me it sounds like a problem with the hard drive or OS, but again, no idea. I hope you can find a solution.

**Comment by xxBoWiExx** [comment] 2020-11-26 16:40
Hi have the same error, but my server kick people and the dedicated server freezes

**Comment by Fenixin** [comment] 2020-11-28 22:08
@xxBoWiExx, if you want some help, plase, give some more information.

**Comment by ikew123** [comment] 2021-01-14 05:55
Same problem here

C:\Users\hw801\Downloads\Minecraft-Region-Fixer-master\Minecraft-Region-Fixer-master>python regionfixer.py -p 4 --delete-corrupted C:\Users\hw801\Desktop\world

Welcome to Region Fixer!
(v 0.3.3)

############################################################
#  Scanning world: ('C:\\Users\\hw801\\Desktop', 'world')  #
############################################################

World info:
There are 2114 region files, 9 player files and 19 data files in the world directory.

-------------------- Checking level.dat --------------------
[WARNING!]: 'level.dat' is corrupted with the following error/s:
         The data file cannot be read

---------------- Scanning UUID player files ----------------
9 of 9|##########################################################|Time: 0:00:00

------------- Scanning old format player files -------------
Info: No files to scan.

---------- Scanning structures and map data files ----------
19 of 19|########################################################|Time: 0:00:00

------------------ Scanning region files -------------------
2114 of 2114|####################################################|Time: 0:00:35


############################################################
# Scan results for: ('C:\\Users\\hw801\\Desktop', 'world') #
############################################################


Unreadable player files:
0a82a36f-e8b2-47af-b205-efc1cb5cea6f.dat
223d17f5-eeac-4ef5-ae2f-4c8b36123ef3.dat
24054c1f-8938-4747-8f6a-52530e8ba8da.dat
4894ea51-a49c-4ac5-8fe2-7ec1510c53ad.dat
5b877eb8-ea82-4ea4-b2a5-f12b07ed5b27.dat
73c7d0f2-d84a-44b9-a4ee-23cfaa979749.dat
8fc93aec-da5b-4f69-9cf7-6694116eaf11.dat
b3efaf33-6c45-4662-a924-95035ff78582.dat
feed2e87-869a-4c02-95c2-4b30f91b2cfa.dat

Unreadable data files:
idcounts.dat
map_0.dat
map_1.dat
map_10.dat
map_11.dat
map_12.dat
map_13.dat
map_14.dat
map_15.dat
map_2.dat
map_3.dat
map_4.dat
map_5.dat
map_6.dat
map_7.dat
map_8.dat
map_9.dat
raids.dat
scoreboard.dat

Chunk problems:
No problems found.


Region problems:
No problems found.


No chunks to delete with status: Corrupted

Here's a link to my world
https://drive.google.com/file/d/1dFM-KCYUrw0rj04ExK-eVetsf9Exe5vI/view?usp=drivesdk

I tried deleting the all the files giving me issues and that didn't work, then I tried replacing them with files from a working world and that doesn't work either. Thanks for the help! Let me know if there is anything else I can do to provide you with more info

**Comment by Fenixin** [comment] 2021-01-16 19:33
@ikew123, sorry, no idea what's going on. Your world is completely fine from region fixer perspective. Could you open a new issue with more detailed information?

**Comment by Fenixin** [comment] 2021-01-16 19:34
@ikew123, something strange is going on in your world. You have around 2000 region files but most of them are empty or almost emtpy.

**Comment by ikew123** [comment] 2021-01-16 21:43
What information do you need? This is a server my friends and I play on and will do whatever it takes!Sent from my Galaxy
-------- Original message --------From: Alejandro Aguilera <notifications@github.com> Date: 1/16/21  12:33 PM  (GMT-07:00) To: Fenixin/Minecraft-Region-Fixer <Minecraft-Region-Fixer@noreply.github.com> Cc: ikew123 <ike630wright@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [Fenixin/Minecraft-Region-Fixer] Any way to repair Unreadable data files: idcounts.dat ? (#138) 
@ikew123, sorry, no idea what's going on. Your world is completely fine from region fixer perspective. Could you open a new issue with more detailed information?

**Comment by Fenixin** [comment] 2021-01-17 14:12
In your first post you said "Same problem here", could you please specify exactly what is your problem with more detail? I mean, this issue has this description:
>A world that I can load into once, save, and exit, cannot be loaded again (freezes on "Reading World Data").

But I'm not really sure that is your problem, is it exactly the same problem for you?

**Comment by Fenixin** [comment] 2021-11-07 09:28
A lot has changed in the world format so I'm going to close this. Feel free to reopen if the problem still persists.

**Closed by Fenixin** 2021-11-07 09:28 UTC
Labels: Bug

**Comment by ScoutMaster64** [comment] 2022-01-03 07:31
> My apologies, my world has always worked and has no issues loading. I'm dealing with a strange problem where when my server shuts down, it just hangs until I manually kill it. One of my troubleshooting steps was to check and see if the issue was caused by invalid or corrupted chunks using your utility. The only error I got was for the `idcounts.dat` being unreadable.

I have a realm open for me and my friends, we're getting timed out sometimes idk what causes it I got the same read from regionfixer as unreadable idcounts.dat, everything else works fine people say it might be an internet thing but it's been running smooth for a week just before this error started happening. Have you found a fix?

**Comment by Fenixin** [comment] 2022-01-03 21:55
Hello!

I'm afraid not. It's theoretically possible to fix this by searching the last map used and writing the ID in the file but it has never been implemented. In part because this is not as important as loosing a region file or a chunk, AFAIK loosing idcounts.dat only affects in game item maps.

You could remove the file and wait for minecraft to regenerate it. As always, backup everything before trying!
